"""Snakemake pipeline for converting raw fastq data to ATAC-seq fragments
"""

import fnmatch
import os

############################### GLOBALS (CHANGE ME) ##########################

ref_dir = 'refdata-cellranger-arc-GRCh38-2020-A-2.0.0' # reference genome
cores = 32 # threads to use
cores_cellRanger = int(cores*0.8) # threads to use in Cell Ranger
mem = 64 # memory to use in Cell Ranger

# input dir, file extension
fastq_dir = 'fastqs'
fastq_ext = '.fastq.gz' 

# output directory
out_dir = 'outputs' 

# software paths
bbduk_path = 'bbmap/bbduk.sh'
cellranger_path = 'cellranger-atac-2.1.0/cellranger-atac'

############################### WORKFLOW #####################################

samples = os.listdir(fastq_ext)
output = [f'{out_dir}/{sample}/complete.txt' for sample in samples]

fastq_paths={}
for sample in samples:

    # Make dict of fastq files {sample : (r1, r2)}
    fastq_paths[sample] = (
      fnmatch.filter(os.listdir(f'{fastq_dir}/{sample}'), f'*1*{fastq_ext}')[0],
      fnmatch.filter(os.listdir(f'{fastq_dir}/{sample}'), f'*2*{fastq_ext}')[0]
    )

    # Make output directories
    working_dir = f'{out_dir}/{sample}'
    filtered_dir = f'{working_dir}/filtered'
    cr_inputs = f'{working_dir}/cellranger_inputs' 

    (os.makedirs(dir) for dir in [working_dir, filtered_dir, cr_inputs]
     if not os.path.exists(dir))
            
rule all:
  input:
    output

rule filter_L1:
  input:
    in1 = lambda wildcards: f'{fastq_dir}/{sample}/{fastq_paths[wildcards.sample][0]}',
    in2 = lambda wildcards: f'{fastq_dir}/{sample}/{fastq_paths[wildcards.sample][1]}'
  output:
    out1 = f'{filtered_dir}/{sample}_linker1_R1.fastq.gz',
    out2 = f'{filtered_dir}/{sample}_linker1_R2.fastq.gz'
  shell:
    '''
    {bbduk_path} \
    in1={input.in1} \
    in2={input.in2} \
    outm1={output.out1} \
    outm2={output.out2} \
    k=30 \
    mm=f \
    rcomp=f \
    restrictleft=103 \
    skipr1=t \
    hdist=3 \
    stats={filtered_dir}/{wildcards.sample}_stats.linker1.txt \
    threads={cores} \
    literal=GTGGCCGATGTTTCGCATCGGCGTACGACT
    '''

rule filter_L2:
  input:
    in1 = f'{filtered_dir}/{sample}_linker1_R1.fastq.gz',
    in2 = f'{filtered_dir}/{sample}_linker1_R2.fastq.gz'
  output:
    out1 = f'{filtered_dir}/{sample}_linker2_R1.fastq.gz',
    out2 = f'{filtered_dir}/{sample}_linker2_R2.fastq.gz'
  shell:
    '''
    {bbduk_path} \
    in1={input.in1} \
    in2={input.in2} \
    outm1={output.out1} \
    outm2={output.out2} \
    k=30 \
    mm=f \
    rcomp=f \
    restrictleft=65 \
    skipr1=t \
    hdist=3 \
    stats={filtered_dir}/{wildcards.sample}_stats.linker2.txt \
    threads={cores} \
    literal=ATCCACGTGCTTGAGAGGCCAGAGCATTCG
    '''

rule split_r2:
  input:
    f'{filtered_dir}/{sample}_linker2_R2.fastq.gz'
  output:
    out1 = f'{cr_inputs}/{sample}_S1_L001_R3_001.fastq',
    out2 = f'{cr_inputs}/{sample}_S1_L001_R2_001.fastq'
  shell:
    '''
    python split_r2.py \
    --input {input} \
    --output_R3 {output.out1} \
    --output_R2 {output.out2}
    '''

rule R1_rename: 
  input:
    f'{filtered_dir}/{sample}_linker2_R1.fastq.gz'
  output:
    f'{cr_inputs}/{sample}_S1_L001_R1_001.fastq.gz'
  shell:
    '''
    cp {input} {output}
    '''

rule cell_ranger:
  input:
    in1 = f'{cr_inputs}/{sample}_S1_L001_R1_001.fastq.gz',
    in2 = f'{cr_inputs}/{sample}_S1_L001_R2_001.fastq',
    in3 = f'{cr_inputs}/{sample}_S1_L001_R3_001.fastq'
  output:
    f'{working_dir}/complete.txt'
  shell:
    '''
    {cellranger_path} count \
    --id={wildcards.sample} \
    --reference={ref_dir} \
    --fastqs={cr_data} \
    --sample={wildcards.sample} \
    --localcores={cores_cellRanger} \
    --localmem={mem} \
    --force-cells=2500
    mv {wildcards.sample} {working_dir}
    touch {output}
    '''